[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
[etherscan]
api_key = { sepolia = "${ETHERSCAN_API_KEY}" }

