[profile.default]
src = "solidity/src"
test = "solidity/test"
out = "out"
libs = ["solidity/lib"]
remappings = ["forge-std/=solidity/lib/forge-std/src/"]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/sRaXLBYz7F8MXT0UFNCx0"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://sepolia.etherscan.io/api" }
