[profile.default]
src = "solidity/src"
test = "solidity/test"
out = "out"
libs = ["solidity/lib"]
remappings = ["forge-std/=solidity/lib/forge-std/src/"]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
api_key = { key = "${ETHERSCAN_API_KEY}" }
