name: CI

on:
  push:
    branches:
      - "**"         # tüm branch'lerde test çalışır
  pull_request:

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      # repo dosyalarını runner'a indir
        uses: actions/checkout@v4

      # ---------- Python testleri ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Run Python tests
        run: |
          python -V
          pytest -q

      # ---------- Foundry kurulum + forge-std ----------
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std
        run: |
          mkdir -p lib
          forge install foundry-rs/forge-std


      # (İsteğe bağlı) Solidity/Foundry testleri
      - name: Run Forge tests
        run: forge test -vvv

  deploy:
    name: Deploy (Foundry)
    runs-on: ubuntu-latest
    needs: build
    # sadece main branch'e push olduğunda ve build başarılıysa çalışsın
    if: needs.build.result == 'success' && github.ref == 'refs/heads/main'
    permissions:
      contents: read

    env:
      # ---- Gerekli gizliler (Settings ▸ Secrets and variables ▸ Actions) ----
      # SEPOLIA_RPC_URL         -> Sepolia (veya Holesky) RPC endpoint
      # DEPLOYER_PRIVATE_KEY    -> 0x önekSİZ ham private key
      # ETHERSCAN_API_KEY       -> (opsiyonel) Etherscan API anahtarı
      RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std
        run: |
          mkdir -p lib
          forge install foundry-rs/forge-std --no-commit

      - name: Deploy contract
        run: |
          forge script solidity/script/Deploy.s.sol:Deploy \
            --rpc-url "$RPC_URL" \
            --private-key "$PRIVATE_KEY" \
            --broadcast -vvv

      # (Opsiyonel) Doğrulama adımını istersen doldurabilirsin
      # Aşağıdaki if, ETHERSCAN_API_KEY ayarlıysa çalışmasını sağlar
      - name: Verify on Etherscan (optional)
        if: env.ETHERSCAN_API_KEY != ''
        run: |
          echo "Eğer istersen buraya forge verify-contract komutunu ekleyelim."
          # Örnek:
          # forge verify-contract \
          #   --chain sepolia \
          #   --num-of-optimizations 200 \
          #   --watch \
          #   <DEPLOYED_CONTRACT_ADDRESS> \
          #   <CONTRACT_PATH>:<CONTRACT_NAME> \
          #   $ETHERSCAN_API_KEY
