name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. pytest -q
name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. pytest -q

  solidity:
    name: Forge tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solidity
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install deps (forge-std)
        run: forge install --no-commit foundry-rs/forge-std
      - name: Run forge tests
        run: forge test -vvv
