name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -v

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std
        working-directory: solidity
        run: |
          mkdir -p lib
          if [ ! -d lib/forge-std ]; then
            forge install foundry-rs/forge-std@v1.9.5 --no-git
          fi

      - name: Run Forge tests
        working-directory: solidity
        run: forge test -vvvv

      - name: Deploy simulation (Foundry script)
        working-directory: solidity
        run: forge script script/Deploy.s.sol -vvvv
