name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
      # 1) Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Python kurulumu
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Python bağımlılıkları (requirements.txt varsa)
      - name: Install Python dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      # 4) Python testleri (varsa)
      - name: Run Python tests
        run: |
          python -V
          pytest -q || true

      # 5) Foundry kur (nightly)
      - name: Install Foundry (nightly)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # 6) forge-std: önce forge install, olmazsa git clone
      - name: Install forge-std (try forge, fallback to git)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p lib
          rm -rf lib/forge-std
          if forge install foundry-rs/forge-std@v1.9.5 --quiet; then
            echo "forge-std installed via forge."
          else
            echo "forge install failed, falling back to git clone..."
            git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
          fi

      # 7) (Opsiyonel) Solidity/Foundry testleri
      - name: Run Forge tests
        run: forge test -vvv

  deploy:
    name: Deploy (Foundry)
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry (nightly)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std (try forge, fallback to git)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p lib
          rm -rf lib/forge-std
          if forge install foundry-rs/forge-std@v1.9.5 --quiet; then
            echo "forge-std installed via forge."
          else
            echo "forge install failed, falling back to git clone..."
            git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
          fi

      # !!! BURAYI kendi ağ seçimine göre ayarla:
      #    SEPOLIA için (ETH_RPC_URL=SEPOLIA_RPC_URL)
      #    HOLESKY için (ETH_RPC_URL=HOLESKY_RPC_URL)
      - name: Deploy contract
        working-directory: .
        env:
          ETH_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}   # veya HOLESKY_RPC_URL
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          forge script solidity/script/Deploy.s.sol:Deploy \
            --rpc-url "$ETH_RPC_URL" \
            --private-key "$PRIVATE_KEY" \
            --broadcast \
            --verify \
            -vvvv
