name: Deploy (Foundry)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry (nightly)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std (try forge, fallback to git)
        run: |
          forge install foundry-rs/forge-std --no-commit || git clone https://github.com/foundry-rs/forge-std lib/forge-std

      - name: Deploy contract
        working-directory: solidity
        env:
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          set -euxo pipefail
          echo "Deploying via Foundry..."
          forge script script/Deploy.s.sol:Deploy \
            --rpc-url "$SEPOLIA_RPC_URL" \
            --private-key "$DEPLOYER_PRIVATE_KEY" \
            --broadcast -vvvv \
            --verify --etherscan-api-key "$ETHERSCAN_API_KEY"
